[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nbsplitter"
version = "1.0.0"
authors = [
    { "name"="Sai Koushik Balusulapalem", email="balusulapalem.saikoushik@gmail.com" },
]
requires-python = ">=3.9"
license = "Apache-2.0"
readme = "README.md"
keywords = ["japanese", "grapheme", "kanji"]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: MacOS",
    "Operating System :: Microsoft",
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Text Processing",
    "Topic :: Text Processing :: Linguistic",
]

dynamic = ["dependencies"]

[project.urls]
Source = "https://github.com/balusulapalemsaikoushik/nbsplitter"

[tool.hatch.build.hooks.custom]
path = "hatch_build.py"

[tool.hatch.metadata.hooks.custom]
path = "hatch_build.py"

[tool.hatch.build]
ignore-vcs = true

[tool.hatch.build.targets.wheel]
packages = ["src/nbsplitter"]
